### ISSUE TITLE
I translate but it won't success

### ISSUE THREAD

**Issue by ptchen314** [TABmk/dmeditor#2]
I translate every thing but the name on the webside won't be change. For example: I translate it like this
![image](https://user-images.githubusercontent.com/64603358/106359389-8a5e4e80-634d-11eb-9dfe-c8c4120d83a1.png)

but the webside look like this 
![image](https://user-images.githubusercontent.com/64603358/106359432-baa5ed00-634d-11eb-84be-836dd74255ca.png)

**Comment by TABmk** [comment]
@jing-shiun Fixed

<img width="958" alt="image" src="https://user-images.githubusercontent.com/7514285/106371034-fb632d80-6370-11eb-9d02-c4e31b68652d.png">

**Comment by ptchen314** [comment]
ok
