### ISSUE TITLE
All right one more bug

### ISSUE THREAD

**Issue by ptchen314** [TABmk/dmeditor#3]
![image](https://user-images.githubusercontent.com/64603358/106391035-48550b80-6426-11eb-90b5-7ad8466d8b66.png)
the config will show the translate title

**Comment by TABmk** [comment]
Fixed. Also added "Clear slot" button, improved buttons style, fixed empty slot editing. Now if you changed language and reloaded page, dropdown shows correct current language.

Still a lot of work to do and if you have any ideas for new features, feel free to open new issue. I added new label "feature wanted" for this
