### ISSUE TITLE
[Feature Request] When we drag the mouse on the item make it we can see the color and lore 

### ISSUE THREAD

**Issue by itz-rj-here** [TABmk/dmeditor#4]
![2022-08-18_18 38 26](https://user-images.githubusercontent.com/86042583/185741951-cded4393-a59d-4666-912b-e6ff4061db7c.png)
like this one and you need to upgrade the lore too its too old one from the newer version. 
Hope it will be added soon and you make a very good design to the deluxemenu editor too. Thanks.

**Comment by TABmk** [comment]
@OPADILOP 

Hi, just updated code and demo. Added lore preview, updated dm options and now multiple rows in textarea are converting to yml arrays

<img width="1090" alt="image" src="https://user-images.githubusercontent.com/7514285/187038781-d79eb4ee-f727-4a6c-888c-e8d9259a320e.png">
