### ISSUE TITLE
Formatting of some config files updated

### ISSUE THREAD

**Issue by KiWinger** [TABmk/dmeditor#5]
'19':
    material: 'COMPASS'
    slot: 19
    display_name: '&b&lBack Spawn'
    lore:
      - '&a/spawn'
      - ''
      - '&7Back Spawn'
    left_click_commands: 
      - '[player] spawn'　　　　　for Deluxemenus-1.13.6
———————————————————————
  19:　　　　　　　　　　　 for deluxemenus-editor
    material: "COMPASS"
    slot: 19
    display_name: "&b&lBack Spawn"
    lore:
      - "&a/spawn"
      - ""
      - "&7Back Spawn"
    left_click_commands: "spawn"

- Among them, 19 need to be wrapped in a single quotation number.
- Commands needs the same format as Lore. The commands need to specify the action, 
like https://wiki.helpch.at/clips-plugins/deluxemenus/options-and-configurations#actions-types
- Replace double quotes with single quotes.

Plz fix ;D

**Comment by TABmk** [comment]
Hi, @KiWinger, thank you for your feedback

> Among them, 19 need to be wrapped in a single quotation number.

There are no restrictions on using numbers in keys by YAML spec. However, if you have a such case, where you need them, I changed the YAML serializer, so you can configure it on the fly.

> Commands needs the same format as Lore

There was an option to create a single key:value if you use one line in `teaxarea` (lore, commands, etc). And if you use multiple lines, it creates an array. As far as I remember, It worked in old DM versions, but just checked, and `lore: 123` not working now. So, this feature has just been removed now.

> The commands need to specify the action

Action types are just text, like other commands. I think it is better to not force users to choose actions for at least two reasons: 1 - actions are optional; 2 - they can be changed anytime in DM, so no sense to keep them up to date in the editor

> Replace double quotes with single quotes

[YAML provides multiple flow scalar styles](https://yaml.org/spec/1.2.2/#73-flow-scalar-styles). IMO, double quotes are better for readability. Anyway, with new options, you can choose any style you like.


The new version was updated at 06702d1bc375338910dca1cf499a8e1c5729265c. [Demo](https://tabmk.github.io/deluxemenus-editor/) is updated too. Clear the cache if you don’t see changes.

Also fixed transparent selection.
